/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package aplicacao;

import aplicacao.ScrollCustomizado;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author robson
 */
public abstract class frmGenericomodal extends javax.swing.JDialog {

    /**
     * Creates new form Teste
     */
    private final String PATH_ICON = "/recurso/estoque-pronto.png";
    
    
    // Aplica estilo a todos os JTextField do frame
    protected void initEstiloGlobal() {
        estilizarTextFields(this); // Aplica ao próprio frame e seus componentes
    }
    
    private void estilizarTextFields(Container container) {
        for (Component c : container.getComponents()) {
            if (c instanceof JTextField) {
                JTextField campo = (JTextField) c;

                campo.setBorder(BorderFactory.createCompoundBorder(
                    new RoundedBorder(new Color(150, 150, 150), 1, 8), // Cor, espessura e raio do arredondamento
                    //BorderFactory.createLineBorder(new Color(150, 150, 150), 1, true), // borda arredondada
                    BorderFactory.createEmptyBorder(2, 5, 2, 5) // padding interno
                ));
                campo.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                campo.setBackground(Color.WHITE);
            } else if (c instanceof Container) {
                estilizarTextFields((Container) c); // recursivo, para painéis internos
            }
            
            if (c instanceof JComboBox) {
                JComboBox campo = (JComboBox) c;

                campo.setBorder(BorderFactory.createCompoundBorder(
                    new RoundedBorder(new Color(150, 150, 150), 1, 8), // Cor, espessura e raio do arredondamento
                    //BorderFactory.createLineBorder(new Color(150, 150, 150), 1, true), // borda arredondada
                    BorderFactory.createEmptyBorder(2, 5, 2, 5) // padding interno
                ));
                campo.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                campo.setBackground(Color.WHITE);
                campo.setPreferredSize(new Dimension(200, 24)); // Exemplo: largura 200, altura 24
                
            } else if (c instanceof Container) {
                estilizarTextFields((Container) c); // recursivo, para painéis internos
            }
        }
    }

    public frmGenericomodal(java.awt.Frame parent, boolean modal) {
                
        super(parent, modal);
        initComponents();
        ImageIcon imageicon = new ImageIcon(getClass().getResource(PATH_ICON));
        this.setIconImage(imageicon.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
