/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;



import java.awt.Container;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTextField;


import javax.swing.border.AbstractBorder; // Para estender AbstractBorder
import java.awt.Component;               // Para o parâmetro 'c' em paintBorder e getBorderInsets
import java.awt.Graphics;                // Para o parâmetro 'g' em paintBorder
import java.awt.Graphics2D;              // Para funcionalidades 2D de desenho
import java.awt.Color;                   // Para definir cores
import java.awt.BasicStroke;             // Para definir a espessura da linha da borda
import java.awt.RenderingHints;          // Para suavizar as bordas (anti-aliasing)
import java.awt.Insets;                  // Para definir o espaçamento interno da borda
import java.awt.geom.RoundRectangle2D;


/**
 *
 * @author robson
 */
public abstract class frmGenerico extends javax.swing.JFrame {

    /**
     * Creates new form frmGenerico
     */
    private final String PATH_ICON="/recurso/estoque-pronto.png"; 
    
    // Aplica estilo a todos os JTextField do frame
    protected void initEstiloGlobal() {
        estilizarTextFields(this); // Aplica ao próprio frame e seus componentes
    }
    
    private void estilizarTextFields(Container container) {
        for (Component c : container.getComponents()) {
            if (c instanceof JTextField) {
                JTextField campo = (JTextField) c;

                campo.setBorder(BorderFactory.createCompoundBorder(
                    new RoundedBorder(new Color(150, 150, 150), 1, 8), // Cor, espessura e raio do arredondamento
                    //BorderFactory.createLineBorder(new Color(150, 150, 150), 1, true), // borda arredondada
                    BorderFactory.createEmptyBorder(2, 5, 2, 5) // padding interno
                ));
                campo.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                campo.setBackground(Color.WHITE);
            } else if (c instanceof Container) {
                estilizarTextFields((Container) c); // recursivo, para painéis internos
            }
        }
    }

    public frmGenerico() {
        initComponents();
        ImageIcon imageicon = new ImageIcon(getClass().getResource(PATH_ICON));
        this.setIconImage(imageicon.getImage());       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
