/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;

//import controller.RelatoriosController;
import dao.DAOFactory;
import dao.ModuloDAO;
import dao.PermissaomoduloDAO;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.List;
//import javax.swing.ImageIcon;
//import modelo.Modulo;
import modelo.Permissaomodulo;



/**
 *
 * @author robson
 */
public class frmPrincipal extends frmGenerico {

    private int idUsuariosecao;
    private int idPermissaosecao;
    //private final String PATH_ICON="/recurso/estoque-pronto.png"; 
    /**
     * Creates new form frmPrincipla
     */
    
    PermissaomoduloDAO permissaomoduloDAO = DAOFactory.criarPermissaomoduloDAO();
    ModuloDAO moduloDAO = DAOFactory.criarModuloDAO();
    
                        
    public frmPrincipal(int idUsuariosecao, int idPermissaosecao) {
        this.idUsuariosecao = idUsuariosecao;
        this.idPermissaosecao = idPermissaosecao; //********
        initComponents();
        
     
        //ImageIcon imageicon = new ImageIcon(getClass().getResource(PATH_ICON));
        //this.setIconImage(imageicon.getImage());
        //lblPermissao.setText(Integer.toString(permissao));
        //lblPermissao.setText(String.valueOf(permissao));
        //lblPermissao.setText(""+permissao);
        // Define o layout do JFrame como GridBagLayout
        getContentPane().setLayout(new GridBagLayout());
        
        // Cria constraints reutilizáveis
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;        // coluna 0
        gbc.anchor = GridBagConstraints.PAGE_START; // centraliza horizontalmente
        gbc.insets = new Insets(10, 10, 10, 10); // margem ao redor

        // Adiciona o JLabel na linha 0
        gbc.gridy = 0; // linha 0
        getContentPane().add(jLabel1, gbc);

        // Adiciona o painel na linha 1
        gbc.gridy = 1; // linha 1
        getContentPane().add(jPanel1, gbc);
    
        this.setResizable(false);
        /*getContentPane().setLayout(new GridBagLayout());
        getContentPane().remove(jPanel1);
        getContentPane().add(jPanel1, new GridBagConstraints());*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEquipamento = new javax.swing.JButton();
        btnUnidade = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnMoviemtacao = new javax.swing.JButton();
        btnPermissao = new javax.swing.JButton();
        btnFabricante = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        btnConfiguracao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPermissao = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        menuFabricante = new javax.swing.JMenuItem();
        menuEquipamento = new javax.swing.JMenuItem();
        menuUnidade = new javax.swing.JMenuItem();
        menuMovimentacao = new javax.swing.JMenuItem();
        menuModulo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patrim - Principal");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTROS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setToolTipText("Cadastros");

        btnEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEquipamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\robson.SRVLISBOAINFO\\Desktop\\ProjPOO\\PatrimonioControl\\PatrimonioControl\\src\\recurso\\gerador-eletrico (1).png")); // NOI18N
        btnEquipamento.setText("Equipamentos");
        btnEquipamento.setEnabled(false);
        btnEquipamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEquipamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipamentoActionPerformed(evt);
            }
        });

        btnUnidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUnidade.setIcon(new javax.swing.ImageIcon("C:\\Users\\robson.SRVLISBOAINFO\\Desktop\\ProjPOO\\PatrimonioControl\\PatrimonioControl\\src\\recurso\\casa-limpa (1).png")); // NOI18N
        btnUnidade.setText("Unidades");
        btnUnidade.setEnabled(false);
        btnUnidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadeActionPerformed(evt);
            }
        });

        btnUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\robson.SRVLISBOAINFO\\Desktop\\ProjPOO\\PatrimonioControl\\PatrimonioControl\\src\\recurso\\adicionar-usuario (1).png")); // NOI18N
        btnUsuario.setText("Usuários");
        btnUsuario.setEnabled(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnMoviemtacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoviemtacao.setIcon(new javax.swing.ImageIcon("C:\\Users\\robson.SRVLISBOAINFO\\Desktop\\ProjPOO\\PatrimonioControl\\PatrimonioControl\\src\\recurso\\movimentacao-de-carga (1).png")); // NOI18N
        btnMoviemtacao.setText("Movimentação");
        btnMoviemtacao.setEnabled(false);
        btnMoviemtacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMoviemtacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMoviemtacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoviemtacaoActionPerformed(evt);
            }
        });

        btnPermissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPermissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/chaveiro.png"))); // NOI18N
        btnPermissao.setText("Permissões");
        btnPermissao.setEnabled(false);
        btnPermissao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPermissao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermissaoActionPerformed(evt);
            }
        });

        btnFabricante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/fabrica.png"))); // NOI18N
        btnFabricante.setText("Fabricante");
        btnFabricante.setEnabled(false);
        btnFabricante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFabricante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabricanteActionPerformed(evt);
            }
        });

        btnModulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/funcional.png"))); // NOI18N
        btnModulo.setText("Funções");
        btnModulo.setEnabled(false);
        btnModulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });

        btnConfiguracao.setIcon(new javax.swing.ImageIcon("C:\\Users\\robson.SRVLISBOAINFO\\Desktop\\ProjPOO\\PatrimonioControl\\PatrimonioControl\\src\\recurso\\configuracao (1).png")); // NOI18N
        btnConfiguracao.setText("Configuração");
        btnConfiguracao.setEnabled(false);
        btnConfiguracao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguracao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMoviemtacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMoviemtacao, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfiguracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patrimônio Control - Estoque e Movimentações");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jMenu1.setText("Cadastro");

        menuPermissao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPermissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/chaveiro (1).png"))); // NOI18N
        menuPermissao.setText("Permissões");
        menuPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPermissaoActionPerformed(evt);
            }
        });
        jMenu1.add(menuPermissao);

        menuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/adicionar-usuario.png"))); // NOI18N
        menuUsuario.setText("Usuários");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuario);

        menuFabricante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/fabrica (1).png"))); // NOI18N
        menuFabricante.setText("Fabricante");
        menuFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFabricanteActionPerformed(evt);
            }
        });
        jMenu1.add(menuFabricante);

        menuEquipamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/gerador-eletrico.png"))); // NOI18N
        menuEquipamento.setText("Equipamentos");
        menuEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEquipamentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuEquipamento);

        menuUnidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/casa-limpa.png"))); // NOI18N
        menuUnidade.setText("Unidades");
        menuUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnidadeActionPerformed(evt);
            }
        });
        jMenu1.add(menuUnidade);

        menuMovimentacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuMovimentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/movimentacao-de-carga.png"))); // NOI18N
        menuMovimentacao.setText("Movimentação");
        menuMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovimentacaoActionPerformed(evt);
            }
        });
        jMenu1.add(menuMovimentacao);

        menuModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/funcional (1).png"))); // NOI18N
        menuModulo.setText("Funções");
        menuModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModuloActionPerformed(evt);
            }
        });
        jMenu1.add(menuModulo);
        jMenu1.add(jSeparator1);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void setarPermissao(){
        // Pegue a lista de permissões
        List<Permissaomodulo> permissaomodulos = permissaomoduloDAO.listarPorPermissao(idPermissaosecao); 
        
        if (idPermissaosecao==1)
            btnConfiguracao.setVisible(true);
        
        // Itera sobre cada objeto Permissaomodulo na lista
        for (Permissaomodulo permissaoModulo : permissaomodulos) {

            // Acessa o nome do módulo a partir do objeto aninhado
            String nomeModulo = permissaoModulo.getModulo().getNome();

            // Verifica se pelo menos uma das permissões está ativa
            boolean temPermissaoAtiva = 
                permissaoModulo.isVisualizar() || 
                permissaoModulo.isInserir() || 
                permissaoModulo.isAlterar() || 
                permissaoModulo.isExcluir();
            
            if (temPermissaoAtiva) {
                // Estrutura de switch para tratar cada módulo
                switch (nomeModulo) {
                    case "USUÁRIO":
                        btnUsuario.setEnabled(true);
                        break;
                    case "PERMISSÃO":
                        btnPermissao.setEnabled(true);
                        break;
                    case "FUNCIONALIDADE":
                        btnModulo.setEnabled(true);
                        break;
                    case "FABRICANTE":
                        btnFabricante.setEnabled(true);
                        break;
                    case "EQUIPAMENTOS":
                        btnEquipamento.setEnabled(true);
                        break;
                    case "UNIDADE":
                        btnUnidade.setEnabled(true);
                        break;
                    case "MOVIMENTAÇÃO":
                        btnMoviemtacao.setEnabled(true);
                        break;
                    case "CONFIGURAÇÃO":
                        btnConfiguracao.setEnabled(true);
                        break;
                    default:
                        // Lógica para módulos não mapeados, se necessário
                        System.out.println("Módulo '" + nomeModulo + "' não possui botões mapeados.");
                        break;
                }
            } else {
                // Estrutura de switch para tratar cada módulo
                switch (nomeModulo) {
                    case "USUÁRIO":
                        btnUsuario.setEnabled(false);
                        break;
                    case "PERMISSÃO":
                        btnPermissao.setEnabled(false);
                        break;
                    case "FUNCIONALIDADE":
                        btnModulo.setEnabled(false);
                        break;
                    case "FABRICANTE":
                        btnFabricante.setEnabled(false);
                        break;
                    case "EQUIPAMENTOS":
                        btnEquipamento.setEnabled(false);
                        break;
                    case "UNIDADE":
                        btnUnidade.setEnabled(false);
                        break;
                    case "MOVIMENTAÇÃO":
                        btnMoviemtacao.setEnabled(false);
                        break;
                    case "CONFIGURAÇÃO":
                        btnConfiguracao.setEnabled(false);
                        break;
                    default:
                        // Lógica para módulos não mapeados, se necessário
                        System.out.println("Módulo '" + nomeModulo + "' não possui botões mapeados.");
                        break;
                }
            }
        }       
    }
    
    
    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        frmUsuario usuario = new frmUsuario(this, true, idUsuariosecao, idPermissaosecao);
        usuario.setVisible(true);
        //new frmUsuario().setVisible(true); 
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        frmUsuario usuario = new frmUsuario(this, true, idUsuariosecao, idPermissaosecao);
        usuario.setVisible(true);
        //new frmUsuario().setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEquipamentoActionPerformed
        frmEquipamento equipamento = new frmEquipamento(this, true, idUsuariosecao, idPermissaosecao);
        equipamento.setVisible(true);
        //new frmEquipamento().setVisible(true);
    }//GEN-LAST:event_menuEquipamentoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btnPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermissaoActionPerformed
        frmPermissao permissao = new frmPermissao(this, true, idUsuariosecao, idPermissaosecao);
        permissao.setVisible(true);
        //new frmPermissao().setVisible(true);
    }//GEN-LAST:event_btnPermissaoActionPerformed

    private void btnFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabricanteActionPerformed
        frmFabricante fabricante = new frmFabricante(this, true, idUsuariosecao, idPermissaosecao);
        fabricante.setVisible(true);
        //new frmFabricante().setVisible(true);
    }//GEN-LAST:event_btnFabricanteActionPerformed

    private void menuFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFabricanteActionPerformed
        frmFabricante fabricante = new frmFabricante(this, true, idUsuariosecao, idPermissaosecao);
        fabricante.setVisible(true);
        //new frmFabricante().setVisible(true);
    }//GEN-LAST:event_menuFabricanteActionPerformed

    private void menuPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPermissaoActionPerformed
        frmPermissao permissao = new frmPermissao(this, true, idUsuariosecao, idPermissaosecao);
        permissao.setVisible(true);
        //new frmPermissao().setVisible(true);        
    }//GEN-LAST:event_menuPermissaoActionPerformed

    private void btnEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipamentoActionPerformed
        frmEquipamento equipamento = new frmEquipamento(this, true, idUsuariosecao, idPermissaosecao);
        equipamento.setVisible(true);
        //new frmEquipamento().setVisible(true);
    }//GEN-LAST:event_btnEquipamentoActionPerformed

    private void btnUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadeActionPerformed
        frmUnidade unidade = new frmUnidade(this, true, idUsuariosecao, idPermissaosecao);
        unidade.setVisible(true);
        //new frmUnidade().setVisible(true); 
    }//GEN-LAST:event_btnUnidadeActionPerformed

    private void menuUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnidadeActionPerformed
        frmUnidade unidade = new frmUnidade(this, true, idUsuariosecao, idPermissaosecao);
        unidade.setVisible(true);
        //new frmUnidade().setVisible(true);
    }//GEN-LAST:event_menuUnidadeActionPerformed

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        frmModulo modulo = new frmModulo(this, true, idUsuariosecao, idPermissaosecao);
        modulo.setVisible(true);
        //new frmModulo().setVisible(true);
    }//GEN-LAST:event_btnModuloActionPerformed

    private void menuModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModuloActionPerformed
        frmModulo modulo = new frmModulo(this, true, idUsuariosecao, idPermissaosecao);
        modulo.setVisible(true);
        //new frmModulo().setVisible(true);    
    }//GEN-LAST:event_menuModuloActionPerformed

    private void btnConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracaoActionPerformed
        frmConfiguracao configuracao = new frmConfiguracao(this, true, idUsuariosecao, idPermissaosecao);
        configuracao.setVisible(true);
        //new frmConfiguracao().setVisible(true);
    }//GEN-LAST:event_btnConfiguracaoActionPerformed

    private void btnMoviemtacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoviemtacaoActionPerformed
        frmMovimentacao movimentacao = new frmMovimentacao(this, true, idUsuariosecao, idPermissaosecao);
        movimentacao.setVisible(true);
        
    }//GEN-LAST:event_btnMoviemtacaoActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        btnConfiguracao.setVisible(false);
        setarPermissao();
        //this.setEnabled(true);
        //this.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void menuMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimentacaoActionPerformed
        frmMovimentacao movimentacao = new frmMovimentacao(this, true, idUsuariosecao, idPermissaosecao);
        movimentacao.setVisible(true);
    }//GEN-LAST:event_menuMovimentacaoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmConfiguracao configuracao = new frmConfiguracao(this, true, idUsuariosecao, idPermissaosecao);
        configuracao.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Exemplo de função de permissao
    /*public boolean podeAcessar(String moduloNome, String acao) {
        for (PermissaoModulo pm : permissoesDoUsuario) {
            if (pm.getModulo().equals(moduloNome)) {
                switch (acao) {
                    case "ver": return pm.isPodeVer();
                    case "criar": return pm.isPodeCriar();
                    case "editar": return pm.isPodeEditar();
                    case "deletar": return pm.isPodeDeletar();
                }
            }
        }
        return false;
    }*/
    
    //Exemplo de uso da função permissão
    /*if (!podeAcessar("Controle de Estoque", "editar")) {
        JOptionPane.showMessageDialog(null, "Você não tem permissão para editar o estoque!");
        return;
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Inicia a janela maximizada
                //new frmPrincipal(permissao).setVisible(true); //new frmPrincipal().setVisible(true); //
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnEquipamento;
    private javax.swing.JButton btnFabricante;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnMoviemtacao;
    private javax.swing.JButton btnPermissao;
    private javax.swing.JButton btnUnidade;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuEquipamento;
    private javax.swing.JMenuItem menuFabricante;
    private javax.swing.JMenuItem menuModulo;
    private javax.swing.JMenuItem menuMovimentacao;
    private javax.swing.JMenuItem menuPermissao;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuUnidade;
    private javax.swing.JMenuItem menuUsuario;
    // End of variables declaration//GEN-END:variables
}
